import Providers from '@/store/Providers'

import { Cart } from '@/components/Cart'
import { Footer } from '@/components/Footer'
import { Header } from '@/components/Header'
import { MenuList } from '@/components/MenuList'
import { Navbar } from '@/components/Navbar'
import { PopularItems } from '@/components/PopularItems'
import { Stories } from '@/components/Stories'
import './globals.css'

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<body className="min-h-screen flex flex-col">
				<Providers>
					<Header />
					<Navbar />
					<div className="max-w-7xl mx-auto">
						<Stories />
						<PopularItems />
						<MenuList />
					</div>
					<Cart />
					{children}
					<Footer />
				</Providers>
			</body>
		</html>
	)
}
