import Providers from '@/store/Providers'

import './globals.css'

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<body className="min-h-screen flex flex-col">
				<Providers>{children}</Providers>
			</body>
		</html>
	)
}
